//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COCInviter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection acceptableRolesSetting {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["acceptableRolesSetting"]));
            }
            set {
                this["acceptableRolesSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maxLeagueTextBoxSetting {
            get {
                return ((int)(this["maxLeagueTextBoxSetting"]));
            }
            set {
                this["maxLeagueTextBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minLevelTextBoxSetting {
            get {
                return ((int)(this["minLevelTextBoxSetting"]));
            }
            set {
                this["minLevelTextBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minAttacksTextBoxSetting {
            get {
                return ((int)(this["minAttacksTextBoxSetting"]));
            }
            set {
                this["minAttacksTextBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minKingTextBoxSetting {
            get {
                return ((int)(this["minKingTextBoxSetting"]));
            }
            set {
                this["minKingTextBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minQueenTextBoxSetting {
            get {
                return ((int)(this["minQueenTextBoxSetting"]));
            }
            set {
                this["minQueenTextBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minWardenTextBoxSetting {
            get {
                return ((int)(this["minWardenTextBoxSetting"]));
            }
            set {
                this["minWardenTextBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minChampionTextBoxSetting {
            get {
                return ((int)(this["minChampionTextBoxSetting"]));
            }
            set {
                this["minChampionTextBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string apiKeySetting {
            get {
                return ((string)(this["apiKeySetting"]));
            }
            set {
                this["apiKeySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minTownhallTextBoxSetting {
            get {
                return ((int)(this["minTownhallTextBoxSetting"]));
            }
            set {
                this["minTownhallTextBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalPlayersFoundSetting {
            get {
                return ((int)(this["totalPlayersFoundSetting"]));
            }
            set {
                this["totalPlayersFoundSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalPlayersInvitedSetting {
            get {
                return ((int)(this["totalPlayersInvitedSetting"]));
            }
            set {
                this["totalPlayersInvitedSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string savedPlayersSetting {
            get {
                return ((string)(this["savedPlayersSetting"]));
            }
            set {
                this["savedPlayersSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection uniquePlayersSetting {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["uniquePlayersSetting"]));
            }
            set {
                this["uniquePlayersSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minTrophiesTextBoxSetting {
            get {
                return ((int)(this["minTrophiesTextBoxSetting"]));
            }
            set {
                this["minTrophiesTextBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minDonationsTextBoxSetting {
            get {
                return ((int)(this["minDonationsTextBoxSetting"]));
            }
            set {
                this["minDonationsTextBoxSetting"] = value;
            }
        }
    }
}
